// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClX6E8RxJKTNVJdqRnOTWV6_-8Z-NBQRE',
    appId: '1:576701692157:web:6a9fabceeaf8c6762c2694',
    messagingSenderId: '576701692157',
    projectId: 'smarthome-d9eff',
    authDomain: 'smarthome-d9eff.firebaseapp.com',
    databaseURL: 'https://smarthome-d9eff-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-d9eff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUANXn7IM-wmVE9FKtTfm9e2kzJHm7KPw',
    appId: '1:576701692157:android:79a35938cdc4998f2c2694',
    messagingSenderId: '576701692157',
    projectId: 'smarthome-d9eff',
    databaseURL: 'https://smarthome-d9eff-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-d9eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ZK7g5KxVH7rsyusbMZHrVgLxrvtQONA',
    appId: '1:576701692157:ios:b878b2ed8efc7b2f2c2694',
    messagingSenderId: '576701692157',
    projectId: 'smarthome-d9eff',
    databaseURL: 'https://smarthome-d9eff-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-d9eff.appspot.com',
    iosBundleId: 'com.example.smartHomeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ZK7g5KxVH7rsyusbMZHrVgLxrvtQONA',
    appId: '1:576701692157:ios:df011f5a1d2a39f82c2694',
    messagingSenderId: '576701692157',
    projectId: 'smarthome-d9eff',
    databaseURL: 'https://smarthome-d9eff-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-d9eff.appspot.com',
    iosBundleId: 'com.example.smartHomeApplication.RunnerTests',
  );
}
